const { WebElement } = require("selenium-webdriver");
const {Builder, By, Key, util} = require("selenium-webdriver");

async function profil3(){
    let driver = await new Builder().forBrowser("chrome").build();
    const actions = driver.actions;
    await driver.get("https://dev.safetysolutions.app/login");
    await driver.findElement(By.xpath("//input[@type='text']")).sendKeys("aiss@example.com",Key.RETURN);
    await driver.sleep(500);
    await driver.findElement(By.xpath("//input[@type='password']")).sendKeys("aiss");
    await driver.sleep(2000);
    await driver.findElement(By.className("MuiLoadingButton-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButtonBase-root jss18 css-1eqougf")).click();
    await driver.sleep(2000);
    await driver.navigate().refresh();
    await driver.sleep(1000);
    await driver.findElement(By.xpath("//*[contains(text(), 'Ustawienia')]")).click();
    await driver.sleep(500);
    await driver.get("https://dev.safetysolutions.app/settings/cameras");
    await driver.sleep(500);
    await driver.findElement(By.className("MuiLoadingButton-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButtonBase-root jss50 css-1eqougf")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.name("name")).sendKeys(Key.chord(Key.COMMAND, 'A' + Key.BACK_SPACE));
    await driver.findElement(By.name("name")).sendKeys("test");
    //await driver.sleep(2000);
    await driver.findElement(By.name("cameraIP")).sendKeys(Key.chord(Key.COMMAND, 'A' + Key.BACK_SPACE));
    await driver.findElement(By.name("cameraIP")).sendKeys("999999999");
    //await driver.sleep(2000);
    //await driver.findElement(By.className("MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-hiddenLabel css-rwl29x")).sendKeys(Key.chord(Key.COMMAND, 'A' + Key.BACK_SPACE));
    //await driver.findElement(By.className("MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-hiddenLabel css-rwl29x")).sendKeys("test");
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1uvydh2")).sendKeys(Key.chord(Key.COMMAND, 'A' + Key.BACK_SPACE));
    await driver.findElement(By.className("MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd MuiAutocomplete-input MuiAutocomplete-inputFocused css-1uvydh2")).sendKeys("test pomieszczenie");
    //await driver.sleep(2000);
    await driver.findElement(By.id("free-solo-with-text-demo-option-0")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.id("mui-component-select-accuracyObject")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-a9equi")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-a9equi")).click();
    await driver.findElement(By.className("MuiBackdrop-root MuiBackdrop-invisible css-esi9ax")).click();
    await driver.findElement(By.className("MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-a9equi")).click();
    await driver.findElement(By.xpath("//*[contains(text(), 'Zapisz')]")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.id("r20")).sendKeys("kamera test");
    //await driver.sleep(2000);
    await driver.findElement(By.name("cameraID")).sendKeys(Key.chord(Key.COMMAND, 'A' + Key.BACK_SPACE));
    //await driver.sleep(2000);
    await driver.findElement(By.name("cameraID")).sendKeys("123212121");
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputHiddenLabel css-1x5jdmq")).sendKeys(Key.chord(Key.COMMAND, 'A' + Key.BACK_SPACE));
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputHiddenLabel css-1x5jdmq")).sendKeys("test");
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiSelect-select MuiSelect-outlined MuiOutlinedInput-input MuiInputBase-input css-qiwgdb")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiMenuItem-root MuiMenuItem-gutters Mui-selected MuiButtonBase-root css-a9equi")).click();
    //await driver.sleep(2000);
    await driver.findElement(by.id("anonymization")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.name("accuracyObject")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-a9equi")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-a9equi")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.className("mui-component-select-accuracyIncident")).click();
    //await driver.sleep(2000);
    await driver.findElement(By.className("MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-a9equi")).click();
    //await driver.sleep(2000);

}
profil3();